---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: debug
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: debug
          image: alpine:latest
          args:
            - "/bin/sh"
            - "-c"
            - "sleep infinity"
