---
- name: "Reset Kubernetes"
  shell: echo $(kubeadm reset && echo 'true') 
  become: yes

- name: "Remove docker images" 
  shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
  become: yes

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: "apt-get purge packages"
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl', 'docker-ce']
    state: absent
    purge: yes
    autoremove: yes
    force: yes

- name: "Remove pod logging"
  file:
    path: "{{ item }}"
    state: absent
  become: True
  loop:
    - /var/log/pods

# Doc: http://manpages.ubuntu.com/manpages/trusty/man8/dphys-swapfile.8.html
- name: Enable Swap
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE=0'
    line: CONF_SWAPSIZE=
  register: swap    

- name: Reboot
  reboot:
    reboot_timeout: 120
