---
# tasks file for master
- name: "Kube reset init & join"
  include_tasks: "kube_reset_init_join.yml"

- name: "Kube reset init & join"
  include_tasks: "kube_flannel.yml"

- name: apply kube content
  include_tasks:
      file: "kube_apply_content.yml"